apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: team8akskv
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "team8akskv"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "e3908920-3216-4081-84da-52bee113d601" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQL-DBNAME       # In this example, 'ExampleSecret'   
          objectAlias: SQL_DBNAME
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-PASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-SERVER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_SERVER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-USER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "0bc49434-b2e1-4033-8045-c96767c39b69"               # the tenant ID containing the Azure Key Vault instance