kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-only
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read-only
subjects:
- kind: Group
  namespace: api
  name: web-dev-aks
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-edit
subjects:
- kind: Group
  namespace: api
  name: web-dev-aks
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-read-only
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read-only
subjects:
- kind: Group
  namespace: web
  name: api-dev-aks
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-edit
subjects:
- kind: Group
  namespace: api
  name: api-dev-aks