kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-read-only
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read-only
subjects:
- kind: Group
  namespace: api
  name: e503d068-8f73-4b52-b720-f53b12bb8213
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-edit
subjects:
- kind: Group
  namespace: api
  name: e503d068-8f73-4b52-b720-f53b12bb8213
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-read-only
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-read-only
subjects:
- kind: Group
  namespace: web
  name: 51361f97-3a86-4df9-8e4b-eac8d9041948
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-edit
subjects:
- kind: Group
  namespace: api
  name: 51361f97-3a86-4df9-8e4b-eac8d9041948