apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5zTGcxNDM4Cg==
  SQL_PASSWORD: eVM4dmo4QWkwCg==
  SQL_SERVER: c3Fsc2VydmVyc2xnMTQzOC5kYXRhYmFzZS53aW5kb3dzLm5ldAo=
  SQL_DBNAME: bXlkcml2aW5nREIK